<!-- learning-summary -->
# Day 1：NumPy ndarray 基础

这一天主要学习 NumPy 中 ndarray 的基本概念和创建方法。

具体内容包括：
- 导入 NumPy，并使用 `np.array()` 创建 0 维、1 维和 2 维数组。
- 查看数组的常用属性：`dtype`、`ndim`、`shape`、`size`。
- 使用 `dtype` 指定数组数据类型。
- 使用 `copy()`、`zeros()`、`ones()`、`empty()`、`full()`、`zeros_like()` 创建数组。
- 使用 `arange()`、`linspace()`、`logspace()` 创建等差和对数间隔数组。
- 使用 `eye()` 和 `diag()` 创建单位矩阵、对角矩阵。
- 练习 NumPy 随机数：`rand()`、`uniform()`、`randint()`、`randn()`。
- 使用 `random.seed()` 固定随机数结果，方便复现实验。


In [4]:
import numpy as np

In [13]:
arr = np.array(5)
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)


5
int64
0
()
1


In [10]:
arr2 = np.array([1,2,3,4])
print(arr2)
print(arr2.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)


[1 2 3 4]
int64
1
(4,)
4


In [12]:
arr3 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr3)
print(arr3.dtype)
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)


[[1 2 3 4]
 [4 5 6 7]]
int64
2
(2, 4)
8


ndarry更高级的创建

In [21]:
list1 = [1,2]
arr4 =np.array(list1,dtype=np.float64)
print(arr4)
print(arr4.dtype)
print(arr4.ndim)

[1. 2.]
float64
1


In [22]:
arr5 = np.copy(arr)
print(arr5)

5


In [23]:
arr6 = np.zeros((2,3))
print(arr6)
print(arr6.dtype)
print(arr6.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
2


In [24]:
arr7 = np.ones((200,))
print(arr7)
print(arr7.dtype)
print(arr7.ndim)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]
float64
1


In [25]:
arr8 = np.empty((2,3))
print(arr8)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
arr9 = np.full((4,4),2026)
print(arr9)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [28]:
arr10 = np.zeros_like(arr9)
print(arr10)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [30]:
arr = np.arange(1,10,1) #start, end ,step
print(arr)

[1 2 3 4 5 6 7 8 9]


In [34]:
arr = np.linspace(0,100,5,dtype=int)#等间隔数列
print(arr)

[  0  25  50  75 100]


In [35]:
arr = np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]


In [38]:
arr = np.logspace(0,4,3,base= 2)#对数间隔数列，
print(arr)#2的0次方 2次方 4次方


[ 1.  4. 16.]


矩阵


In [41]:
ARR = np.eye(3,4,dtype=int)
print(ARR)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [43]:
ARR = np.diag([5,2,1,3])
print(ARR)

[[5 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 3]]


In [44]:
#随机数
ARR = np.random.rand(2,3)
print(ARR)

[[0.4220127  0.72391978 0.96043497]
 [0.99085856 0.43329556 0.62692204]]


In [45]:
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[3.11402909 3.13943725 3.14811013]
 [4.46785251 5.47838966 3.10071676]]


In [47]:
ARR = np.random.randint(2,30,(2,3))

print(ARR)

[[ 7 27 23]
 [12 28 12]]


In [50]:
ARR = np.random.randn(2,3)

print(ARR)

[[-0.42288984 -0.70424643  1.33800682]
 [ 0.94234506 -0.17793079 -1.12422705]]


In [59]:
np.random.seed(20)#创建一个种子
ARR = np.random.randint(1,10,(2,3))
print(ARR)

[[4 5 7]
 [8 3 1]]


数据类型
