<!-- learning-summary -->
# Day 2：NumPy 数组操作与常用函数

这一天主要学习 ndarray 的索引、切片、条件筛选、数组运算和常用统计函数。

具体内容包括：
- 创建布尔类型数组，理解 `dtype=bool`。
- 练习一维数组和二维数组的索引、切片。
- 使用条件表达式筛选数组，例如 `arr[arr > 30]`。
- 学习广播机制，理解不同形状数组之间的运算。
- 使用 `@` 做矩阵乘法。
- 练习常用数学函数：`sqrt()`、`exp()`、`log()`、`abs()`、`power()`、`round()`、`ceil()`。
- 使用 `isnan()` 判断缺失值。
- 练习统计函数：`sum()`、`mean()`、`median()`、`var()`、`max()`、`argmax()`、`percentile()`、`cumsum()`。
- 使用比较函数和条件选择：`greater()`、`where()`、`select()`。
- 学习排序、去重、拼接、拆分和数组形状变换：`sort()`、`unique()`、`concatenate()`、`split()`、`reshape()`。
- 初步理解 `axis=0` 和 `axis=1` 的含义。


数据类型


In [1]:
import numpy as np

In [2]:
arr = np.array([1,0,1,0],dtype=bool)
print(arr)

[ True False  True False]


索引，切片

In [18]:
arr = np.random.randint(1,50,20)
print(arr)
print(arr[5])
print(arr[:])#全部数据
print(arr[2:4])#左开右闭
print(arr[arr>30])
print(arr[(arr>20)&(arr<50)])
print(arr[slice(2,4)])


[12 21 20 17 48 14  4 23 14 12  4 39 10 43 11  8 49 15  2  2]
14
[12 21 20 17 48 14  4 23 14 12  4 39 10 43 11  8 49 15  2  2]
[20 17]
[48 39 43 49]
[21 48 23 39 43 49]
[20 17]


In [28]:
arr = np.random.randint(1,100,(4,8))
print(arr)
print(arr[1,3])
print(arr[1][3])
print(arr[1,:])
print(arr[:][3])#第四行
print(arr[:,3])#第4列
print(arr[2][arr[2]>30])#行数据


[[86 20 52  6 50  9 43 47]
 [81 84 59 51 19 76 11  1]
 [ 3 52 47 64 39 10  5 65]
 [31 33 65 71 74 22 91  4]]
51
51
[81 84 59 51 19 76 11  1]
[31 33 65 71 74 22 91  4]
[ 6 51 64 71]
[52 47 64 39 65]


运算（对应位置相加减）

In [29]:
arr = np.array([1,2,3])
print(arr+3)

[4 5 6]


In [31]:
#广播
a= np.array([1,2,3])#1*3
b = np.array([[1],[2],[3]])#3*1
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


矩阵运算

In [32]:
a= np.array([1,2,3])#1*3
b = np.array([[1],[2],[3]])#3*1
print(a@b)#矩阵的乘法

[14]


numpy其它常用函数

In [40]:
print(np.sqrt([1,4,9]))
print(np.exp(1))#e^x
print(np.log(np.exp(1)))#ln
print(np.abs(-1))
print(np.power(a,3))
print(np.round([3.2,4.5,4.51]))
print(np.ceil([3.1]))#向下取整是floor


[1. 2. 3.]
2.718281828459045
1.0
1
[ 1  8 27]
[3. 4. 5.]
[4.]


In [41]:
np.isnan([1,2,np.nan,4])

array([False, False,  True, False])

In [52]:
arr2 = np.random.randint(1,20,8)
print(arr2)
print(np.sum(arr2))
print(np.mean(arr2))#平均值
print(np.median(arr2))#中位数
print(np.var(arr2))#方差    std是标准差，即sqrt（方差）
print(np.max(arr2),np.argmax(arr2))#后面是索引
print(np.percentile(arr2,20))
print(np.cumsum(arr2))#还有一个cumprod


[ 8 17 10 13 14 18  5 13]
98
12.25
13.0
16.9375
18 5
8.8
[ 8 25 35 48 62 80 85 98]


比较函数，基本上返回bool

In [60]:
print(np.greater([3,4,5,6,7],4))#还有less equal
arr3 = np.array([1,2,3,4,5])
print(np.where(arr3>2,arr3,0))
arr4 = np.random.randint(1,100,8)
print(arr4)
print(np.where(arr4>=60,'pass','fail'))
print(np.select([arr4>80,(arr4>60)&(arr4<=80),arr4<60],['1','2','3'],default='4'))

[False False  True  True  True]
[0 0 3 4 5]
[81 47 96 46 18 31 22 43]
['pass' 'fail' 'pass' 'fail' 'fail' 'fail' 'fail' 'fail']
['1' '3' '1' '3' '3' '3' '3' '3']


排序

In [64]:
np.random.seed(0)
arr5  = np.random.randint(1,100,20)
print(arr5)
arr5.sort()
print(arr5)
print(np.sort(arr5))
print(np.unique(arr5))#去重同时排序


[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


拼接

In [65]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [67]:
print(np.split(arr5,4))
print(np.split(arr5,[6,12,18]))

[array([10, 13, 22, 37, 40], dtype=int32), array([45, 47, 48, 59, 65], dtype=int32), array([66, 68, 68, 71, 84], dtype=int32), array([88, 88, 89, 89, 89], dtype=int32)]
[array([10, 13, 22, 37, 40, 45], dtype=int32), array([47, 48, 59, 65, 66, 68], dtype=int32), array([68, 71, 84, 88, 88, 89], dtype=int32), array([89, 89], dtype=int32)]


In [69]:
print(np.reshape(arr5,[4,5]))

[[10 13 22 37 40]
 [45 47 48 59 65]
 [66 68 68 71 84]
 [88 88 89 89 89]]


axis=0是每列    axis=1是每行